apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-mongodb-deployment
  labels:
    app: order-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-mongodb
  template:
    metadata:
      labels:
        app: order-mongodb
    spec:
      containers:
      - name: rvstore-orders-mongodb
        image: mongo
        env:
         - name: MONGO_INITDB_ROOT_USERNAME
           value: "mongoadmin"
         - name: MONGO_INITDB_ROOT_PASSWORD
           value: "secret"
        ports:
        - containerPort: 27017
